#!/bin/bash

##################################################
# System
##################################################

alias dnsfix="dscacheutil -flushcache"
alias c="clear"
alias h="history"
alias l="ls -alhFGf"
alias ip="ifconfig | grep \"inet \" | grep -v 127.0.0.1 | cut -d\  -f2"
alias flushdscache="dscacheutil -flushcache"
alias hosts="sudo ${EDITOR} /etc/hosts"

# List all users
alias users="dscl . list /Users | grep -v '^_'"

##################################################
# Development
##################################################

# Shortcuts
alias home="cd ~"
alias dev="cd ${HOME}/Dev"
alias hu="cd ${HOME}/Dev/humani.se"
alias ow="cd ${HOME}/Dev/overwine.io"
alias mc="cd ${HOME}/Dev/moneyclip"
alias superpups="cd ${HOME}/Dev/SuperPups"
alias bb="cd ${HOME}/Dev/BlogBox"

# Ruby
alias be="bundle exec"                       # Bundler
alias rb="rbenv"                             # RbEnv
alias rehash="rbenv rehash"                  # Refresh RbEnv's shims
alias powr="touch ${HOME}/.pow/restart.txt"  # Pow
alias rails-s-local="rails s -b 0.0.0.0"     # Network Accessible

# Electron
alias electron="/Applications/Electron.app/Contents/MacOS/Electron"

##################################################
# Dotfiles
##################################################

# alias dotfiles="cd ${DOTFILES}"
alias ea="${EDITOR} ${DOTFILES}/bash/aliases && reload"       # Edit Aliases
alias ef="${EDITOR} ${DOTFILES}/bash/functions && reload"     # Edit Functions
alias ev="${EDITOR} ${DOTFILES}/bash/variables && reload"     # Edit Variables
alias es="${EDITOR} ${DOTFILES}/bash/secrets && reload"       # Edit Secrets
alias ei="${EDITOR} ${DOTFILES}/bash/initializers && reload"  # Edit Initializers
alias reload="source ${HOME}/.bash_profile"

##################################################
# Miscellaneous
##################################################

alias m="cmatrix"
