#!/bin/bash

##################################################
# System
##################################################

alias c="clear"
alias h="history"
alias l="ls -alshGt"
alias hosts="sudo ${EDITOR} /etc/hosts"

##################################################
# Production
##################################################

# Sites
alias hu="cd /srv/humani.se"
alias bb="cd /srv/BlogBox"

# Nginx
alias nginx-dir="cd ${NGINX_DIR}"

# Ruby / Rails
alias be="bundle exec"   # Bundler

# Temporary
alias giannacodes="cd /srv/gianna.codes"
alias superpups="cd /srv/superpups"

##################################################
# Dotfiles
##################################################

alias dotfiles="cd ${DOTFILES}"
alias ea="${EDITOR} ${DOTFILES}/bash/aliases && reload"    # Edit Aliases
alias ef="${EDITOR} ${DOTFILES}/bash/functions && reload"  # Edit Functions
alias ev="${EDITOR} ${DOTFILES}/bash/variables && reload"  # Edit Variables
alias es="${EDITOR} ${DOTFILES}/bash/variables && reload"  # Edit Secrets
alias reload="source ${HOME}/.bash_profile"
