#!/bin/bash

###########################
# Utility
###########################

# Replaces whitespaces with underscores for
# every file in the specified directory.
function replace_whitespace {
  local renamed=0
  if [ "${1}" ] && [ -d "${1}" ]; then
    for filename in "${1}"/*; do
      echo "${filename}" | grep -q " "
      if [ $? -eq 0 ]; then
        mv "${filename}" $(echo "${filename}" | sed -e "s/ /_/g")
        let renamed+=1
      fi
    done
    echo "${renamed} file(s) renamed."
  else
    echo "Invalid path."
  fi
}

###########################
# Funny Or Die
###########################

function fod {
  cd "${HOME}/Dev/funnyordie"
  if [[ $1 == "restart" || $1 == "r" ]]
  then
    sudo powify server restart
  elif [[ $1 == "t" || $1 == "tail" ]]
  then
    tail -f "${HOME}/Dev/funnyordie/log/development.log"
  fi
}

###########################
# Dotfiles
###########################

# TODO: link function
# * should comment out all bash initialization scripts and source the .dotfile version

# TODO: unlink function
# * should remove sourcing of .dotfile initializers and uncomment bash initialization scripts

function dotfiles {
  if [[ $1 == "link" ]]
  then
    timestamp=$(($(date +'%s * 1000 + %-N / 1000000')))
    for dotfile in $DOTFILES/config/*; do
      local target="${HOME}/.${dotfile##*/}"
      if [ -f $target ]; then
        mv $target "${target}.backup.${timestamp}"
        echo "${target} exists! Creating backup..."
      fi
      ln -s $dotfile $target
      echo -e "${dotfile##*/} linked successfully\n"
    done
  elif [[ $1 == "unlink" ]]
  then
    echo "todo"
    # Iterate through home folder to find backup conf files for dotfiles/config.
    # If exists, delete link, restore latest backup.
  else
    cd "${DOTFILES}"
  fi
}

#   ln -s "${DOTFILES}/config/.gitconfig" "${HOME}/.gitconfig"
