#!/bin/bash

###########################
# Initializers
###########################

# Initialize Ruby Environment
eval "$(rbenv init -)"

# Bash Completion
if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
  complete -o default -F _git g
fi

# End Message
printf "${RED}reloaded bash${NO_COLOR}\n";

# Quote of the Moment
random-quote
