#!/bin/bash

###########################
# Initializers
###########################

# Initialize Ruby Environment
eval "$(rbenv init -)"

# End Message
printf "${RED}reloaded bash${NO_COLOR}\n";

# Quote of the Moment
#random-quote
