#!/bin/bash

##################################################
# Initializers
##################################################

# Initialize Ruby Environment
if which rbenv > /dev/null; then
  eval "$(rbenv init -)";
fi

# Bash Completion
if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
  complete -o default -F _git g
fi

# End Message
printf "${RED}reloaded bash${NO_COLOR}\n";

# Amazing Fact
amazing-fact
