#!/bin/bash

####################################
# Environment Variables
####################################

# System
export EDITOR=vi

# Perl5 CPAN
PERL_MB_OPT="--install_base \"/Users/jeff/perl5\""; export PERL_MB_OPT;
PERL_MM_OPT="INSTALL_BASE=/Users/jeff/perl5"; export PERL_MM_OPT;

# NOTE: Maybe brew already does this? RbEnv commands were being duplicated.
# Rbenv (Ruby Environment management)
# export PATH="$HOME/.rbenv/bin:$PATH"
